rewrite script in bath

diff --git a/scripts/setup-install-env b/scripts/setup-install-env
--- a/scripts/setup-install-env
+++ b/scripts/setup-install-env
@@ -1,5 +1,9 @@
-#!/usr/bin/env fish
-
-echo  "This  is  setup-install-env"
-echo
-echo "$PATH"
+if [[ ! -e ./evilwoods-nixos-config/.git ]]; then
+    git clone --depth 1 git@github.com:sttagent/evilwoods-nixos-config.git || {
+        echo "ERROR: failed to clone evilwoods-nixos-config repo."
+        exit 1
+    }
+else
+    echo "INFO: local copy of evilwoods-nixos-config repo already exists."
+    exit
+fi
